version: "3.9" # Эту строку можно удалить, если Docker выдаёт предупреждение

services:
  postgres:
    image: postgres
    container_name: desktop_postgres
    ports:
      - "5433:5432" # внешний:внутренний
    environment:
      POSTGRES_DB: desktopdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
