server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/desktopdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Позволим фронту стучаться к API
cors:
  allowed-origins: "*"
