spring:
  datasource:
    url: jdbc:postgresql://dpg-d1gfom21i9vc73ajmpdg-a.oregon-postgres.render.com:5432/desktop_db
    username: desktop_db_user
    password: ВСТАВЬ_СЮДА_СВОЙ_ПАРОЛЬ_ИЗ_RENDER
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
